### ISSUE TITLE
Relative paths do not work in simplified data sections

### ISSUE THREAD

**Issue by derkork** [derkork/simplegen#11]
Given this section:

```yaml
transformations:
   - data: 
       - "/Foo/Bar/Baz/../../mydata.yml"
       ...

   - data: 
       - basePath: "/Foo/Bar/Baz/../../"
          includes: mydata.yml
          ...
```
The first and the second transformation should basically yield the same result. However the first transformation yields and empty file set while the second one yields one file (as it should).

It seems to work correctly for templates, though:

```yaml
    template: "{{ 'simplegen.shared' | sp }}/templates/configuration_metadata.json.j2"

```
