### ISSUE TITLE
Better support for multiple functions in a single file

### ISSUE THREAD

**Issue by derkork** [derkork/simplegen#17]
If you have one javascript file with many functions you need to repeat the file declaration all the time:

```
customFilters:
 - script: filters/myFunctions.js
   function: oneFunction

 - script: filters/myFunctions.js
   function: otherFunction

```

It would be nice if we could avoid the duplicate declaration like:

```
customFilters:
 - script: filters/myFunctions.js
   function: 
     - oneFunction
     - otherFunction
```
