### ISSUE TITLE
Allow additional input formats.

### ISSUE THREAD

**Issue by derkork** [derkork/simplegen#24]
It would be nice if we could also use other input formats like CSV or XML or TOML as input in addition to YAML/JSON. These formats could be converted to a fixed data structure on the fly. E.g. for CSV:

```csv
Column1;Column2;Column3;
value1;value2;value3;
value4;value5;value6;

```
and configured like this:

```yaml
data:
    - includes: myfile.csv
      type: csv
      root: myfile
```

Could internally yield:
```yaml
myfile:   #this was specified as "root"
  - Column1: value1
    Column2: value2
    Column3: value3
  - Column1: value4
    Column2: value5
    Column3: value6
```

Similarly for XML:

```xml
<root>
   <foo bar="baz">
     <entries>
         <lorem ipsum="dolor">sit amet</lorem>
         <lorem ipsum="dolor">sit amet 2</lorem>
     </entries>
     <remarks/>
  </foo>
</root>
```

```yaml
root:
   foo:
     "@bar": baz
      entries:
         - lorem:
               "@ipsum" : dolor
               __text: sit amet
        - lorem:
               "@ipsum" : dolor
               __text: sit amet 2
       remarks: 
            __text: ""
```

Or TOML:

```toml
[foo]
bar="baz"
```

```yaml
foo:
  bar: "baz"
```
