### ISSUE TITLE
Allow to use multiple config files

### ISSUE THREAD

**Issue by derkork** [derkork/simplegen#26]
For re-using custom javascript filters it would be useful if you could package a filter up with with it's config definition and re-use that everywhere. One way of doing this is putting filter + config into a JAR, use Maven's dependency plugin to unpack that and then be able to refer to the unpacked config files from the main config file:

e.g.

```yaml
includes:
     - unpacked/myfilter1.yaml
     - unpacked/myfilter2.yaml

transformations:
 ....
```
